baseURL: "https://example.com"
languageCode: "en-us"
title: "Mật Táo Đỏ Tâm An"
pygmentsstyle: 'monokai'
paginate: 6
social:
  facebook: "https://facebook.com/mattaodo"
  instagram: "https://www.instagram.com/mattaodobomau"
  email: "mailto:kinhdoanh@tamannatural.vn"
taxonomies:
  author: authors
